# ===================================================================
# 机器人场馆精准坐标配置文件 (waypoint.yaml)
# ===================================================================

waypoints:
  # 出发区
  start:
    x: 0.052
    y: 0.025
    z: 0.007
    w: 0.999

  # 任务一：迎宾引导目的地
  shenzhen:
    x: 1.066
    y: 1.215
    z: 0.000
    w: 0.994

  beijing:
    x: 2.533
    y: 0.207
    z: 0.000
    w: 0.993

  guangzhou:
    x: 2.509
    y: 1.199
    z: 0.000
    w: 0.994

  jilin:
    x: 2.506
    y: 2.205
    z: 0.000
    w: 0.995

  shanghai:
    x: 1.056
    y: 2.205
    z: 0.000
    w: 0.999
