# ===================================================================
# 机器人场馆坐标配置文件 (waypoints.yaml)
# ===================================================================

waypoints:
  # 出发区 / 充电桩位置
  start:
    x: 0.026
    y: -0.008
    w: 0.676

  # 任务一：迎宾引导目的地（深圳馆）
  /*- Translation: [1.066, 1.180, 0.000]
- Rotation: in Quaternion [0.000, -0.000, -0.004, 1.000]
            in RPY (radian) [0.000, -0.000, -0.009]
            in RPY (degree) [0.002, -0.001, -0.497]
*/
  shenzhen:
    x: 1.061
    y: 1.119
    w: 1.0

  # 任务二：巡检目的地（北京馆）
/*
- Translation: [2.449, 0.335, -0.000]
- Rotation: in Quaternion [0.000, 0.000, 0.008, 1.000]
            in RPY (radian) [0.000, 0.000, 0.016]
            in RPY (degree) [0.000, 0.000, 0.924]
*/            

  beijing:
    x: 2.521
    y: 0.117
    w: 1.0

 # 广州馆
/*- Translation: [2.397, 1.305, 0.000]
- Rotation: in Quaternion [0.000, -0.000, 0.011, 1.000]
            in RPY (radian) [0.000, -0.000, 0.022]
            in RPY (degree) [0.000, -0.000, 1.245]
*/

# 吉林馆
/*- Translation: [2.334, 2.157, -0.000]
- Rotation: in Quaternion [0.000, -0.000, 0.015, 1.000]
            in RPY (radian) [0.000, -0.000, 0.030]
            in RPY (degree) [0.000, -0.000, 1.724]
*/

# 上海馆
/*- Translation: [0.994, 2.067, -0.000]
- Rotation: in Quaternion [0.000, -0.000, 0.007, 1.000]
            in RPY (radian) [0.000, -0.000, 0.014]
            in RPY (degree) [0.000, -0.000, 0.783]
*/
  shanghai:
    x: 4.5
    y: -1.2
    w: 1.0
