patrol_waypoints:
  - id: 1
    name: "jiling" # 吉林馆
    x: 2.480
    y: 2.181
    z: 0.0
    w: 1.0
  - id: 2
    name: "guangzhou" # 广州馆
    x: 2.474
    y: 1.162
    z: 0.0
    w: 1.0
  - id: 3
    name: "beijing" # 北京馆
    x: 2.444
    y: 0.195
    z: 0.0
    w: 1.0
  - id: 4
    name: "shengzhen" # 深圳馆
    x: 0.997
    y: 1.218
    z: 0.0
    w: 1.0
  - id: 5
    name: "shanhai" # 上海馆
    x: 1.051
    y: 2.187
    z: 0.0
    w: 1.0
